# Generated by Django 3.1 on 2021-03-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
